version: '2'

networks:
  uos_backend_network:
    ipam:
      driver: default
      config:
      - subnet: 173.18.212.0/24
services:
  backend:
    container_name: ucom_backend
    build:
      dockerfile: ./etc/docker/nodejs/Dockerfile
      context: ./
    depends_on:
      - db_test
      - rabbitmq
    working_dir: /var/www/ucom.backend
    environment:
      - NODE_ENV=test
    volumes:
      - ./:/var/www/ucom.backend
    extra_hosts:
      - "uos-backend-postgres-test.dev:173.18.212.11"
      - "uos-backend-rabbitmq.dev:173.18.212.20"
    networks:
      uos_backend_network:
        ipv4_address: 173.18.212.30
  db_test:
    container_name: ucom_backend_db_test
    hostname: uos-backend-postgres-test.dev
    image: postgres:10.6
    environment:
      - POSTGRES_USER=uos
      - POSTGRES_PASSWORD=uos
      - POSTGRES_DB=uos_backend_app
    networks:
      uos_backend_network:
        ipv4_address: 173.18.212.11
  rabbitmq:
    container_name: ucom_backend_rabbitmq
    hostname: uos-backend-rabbitmq.dev
    image: rabbitmq:3.7.7-management
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    networks:
      uos_backend_network:
        ipv4_address: 173.18.212.20